apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: workspace
  labels: 
    name: api
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: 116521305120.dkr.ecr.us-east-1.amazonaws.com/3-tier-back-end
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 8080
